version: '3.8' # 文件的语法结构的版本

services:
  db:
    image: mysql:latest # specify image（镜像），下载的一个分装环境，latest 就是最新版本
    environment: # 定义环境变量
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: twitch
      MYSQL_ROOT_PASSWORD: secret # 由于只是开发用，所以密码弱没关系
      TZ: UTC # timezone, utc 是一个标准的 tz, 统一时区
    volumes:
      - mysql-local:/var/lib/mysql # 数据库存东西的地方
    ports:
      - 3308:3306 # 左边是自己电脑的（真正的），接到右边docker的虚拟端口，端口映射。Spring Boot的网卡端口是8080
# permanent storage of data.
volumes:
  mysql-local: # 向电脑申请划出一块空间用来存储，即使这里没有写